
<?php
function kyle_menu() {
    $items['ajax-dna-wrapper/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'kyle_callback',
            'page arguments' => array(1,2),
            'type' => MENU_CALLBACK,
    );
    return $items;
}

function kyle_callback($js, $node_id) {
    $node = node_load($node_id);

    if ($js == 'nojs') {
      drupal_goto('node/' . $node->nid);
    }

    $build = node_view($node);
    $html = render($build);

    $commands = array();
    $commands[] = ajax_command_html('#ajax-dna-wrapper', $html);

    print ajax_render($commands);
    exit;
}
